Use usize instead of c_uint for file mode
When `c_uint` is used the following error is triggered:

```
./src/archiver.zig:90:74: error: expected type 'c_uint', found 'usize'
  try write_file_record(&foilz_writer, index, file_buffer, stat.mode);
```